### ISSUE TITLE
Needed to change the order of the 'create' command's parameters

### ISSUE THREAD

**Issue by gdfelt** [Louisvh/TugShuttle#5]
Just a note that I needed to put the droplet name toward the beginning of the command instead of at the end in order to run it:

`tugboat create tugshuttle-to-$region -r $region -s 512mb -i debian-8-x64 -k $keyID 
`

Must have been a recent change to the way the tugboat command works.

**Comment by Louisvh** [comment]
Can't reproduce, but changing this shouldn't break anything. Fixed in the latest commit.
